default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: livemusicarchive2_development

test:
  <<: *default
  database: livemusicarchive2_test

production:
  <<: *default
  database: livemusicarchive2_production
  username: livemusicarchive2
  password: <%= ENV['LIVEMUSICARCHIVE2_DATABASE_PASSWORD'] %>
